Name = "Notting Hill Coffee Project"
Location = "63 Notting Hill Gate, London, W11 3JS"
Version = 1 # Format versioning 

[VisitDate.1649426857] # Epoch Unix Timestamp https://www.unixtimestamp.com
    [Comfort]
        Seating = 0 # Neutral
        Temperature = 0
        Noise = -1
        Notes = "Few seats close to the counter and the entrance. Constant neutral music playing. Chilli at times."
    
    [Sustenance]
        espresso = 1 # Good
        # blend = # No idea
        water = 1
        Notes = "Filtered tap water, self refills."
    
    [Service]
        Power = 0
        Wifi = -1 # See notes # - check for annoying signup, risky data, security
        Staff = "Busy, friendly once they pay attention to you, if they do."
        Notes = "Slightly inconveniently places sockets, no USB. Couldn't ask for wifi because I didn't want wait longer. Maybe ask for it while ordering?"
